catbuffer README is outdated
nemtech/catbuffer pull request #58
Opened 2020-10-20 10:59 UTC by segfaultxavi

Since catbuffer and catbuffer-generators are separate
repos, the commands in the README were not
accurate.
Fixes #55

2020-10-21 14:50 UTC, Jaguar0625 requested changes

2020-10-21 14:50 UTC, Jaguar0625 commented on README.md
> +However, it is much more convenient to use the ``catbuffer-generators`` helper scripts. For instance, you can generate C++ code for all the schemas running the following command (from the ``catbuffer
by `catbuffer-generators` do you mean `catbuffer`? 

scripts in this repo should run without needing generators project.

e.g. 
```
bash ./scripts/generate_all.sh cpp_builder /catapult
```

2020-10-21 14:50 UTC, Jaguar0625 commented on README.md
> +scripts/generate_all.sh cpp_builder
i would note somewhere if not already that scripts require bash v5+

2020-10-21 14:50 UTC, Jaguar0625 commented on README.md
> +From the ``catbuffer-generators`` folder:
i'm not sure why this readme is referring to another project?

2020-10-21 14:59 UTC, segfaultxavi commented
The existing installation instructions said that `catbuffer` must be cloned inside `catbuffer-generators` (as if it was a git submodule) and I continued with that.

I can make the instructions for `catbuffer` completely independent from `catbuffer-generators`, and then add instructions to the later (whose README is currently empty). Would this approach work? Is `catbuffer` really usable without the other project?

2020-10-21 15:02 UTC, Jaguar0625 commented
You need catbuffer-generators project for first example
```
PYTHONPATH=. python3 catbuffer/main.py --schema catbuffer/schemas/transfer/transfer.cats --include catbuffer/schemas --generator cpp_builder
```

But none of the other examples should require it.

2020-10-23 10:22 UTC, segfaultxavi commented on README.md
> +scripts/generate_all.sh cpp_builder
My bash is 4.4 and it seems to be working fine. Are you sure we need to include this comment?

2020-10-23 10:24 UTC, segfaultxavi commented on README.md
> +However, it is much more convenient to use the ``catbuffer-generators`` helper scripts. For instance, you can generate C++ code for all the schemas running the following command (from the ``catbuffer
Done

2020-10-23 10:24 UTC, segfaultxavi commented on README.md
> +From the ``catbuffer-generators`` folder:
Done

2020-10-23 14:27 UTC, Jaguar0625 requested changes
I guess you don't like commas. :joy:

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +Using catbuffer-generators developers can generate builder classes for a given set of programming languages. For example, the [Symbol SDKs](https://nemtech.github.io/sdk) use the generated code to op
comma after generators

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +Using catbuffer-generators developers can generate builder classes for a given set of programming languages. For example, the [Symbol SDKs](https://nemtech.github.io/sdk) use the generated code to op
operate => interact/manipulate

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +> When no generator is given input files are parsed and checked for validity but not output files are created.
comma after given

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +> When no generator is given input files are parsed and checked for validity but not output files are created.
not => no

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +In order to produce any output file the [catbuffer-generators](https://github.com/nemtech/catbuffer-generators) project is needed. Please see this project's usage examples.
comma after file

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +However, ``catbuffer`` can still be used on its own to parse input files and check for their validity:
delete for

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
> +scripts/generate_all.sh
you might want to mention this requires bash 5.0+

2020-10-23 14:27 UTC, Jaguar0625 commented on README.md
>  Copyright (c) 2018 Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp Licensed under the [MIT License](LICENSE)
copyright is outdated, after fernando updates

2020-10-23 14:43 UTC, segfaultxavi commented on README.md
> +scripts/generate_all.sh
Sure? It seems to work fine with my bash 4.4

2020-10-23 14:44 UTC, segfaultxavi commented on README.md
>  Copyright (c) 2018 Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp Licensed under the [MIT License](LICENSE)
Please advice on what should be the new Copyright notice.

2020-10-23 14:47 UTC, segfaultxavi commented
I was under the impression commas after introductory sentences were mostly optional:
https://www.grammarly.com/blog/commas-after-introductory-phrases/
But I'll adapt to the style of the project, of course.

2020-10-23 14:47 UTC, segfaultxavi commented on README.md
> +However, ``catbuffer`` can still be used on its own to parse input files and check for their validity:
Done

2020-10-23 14:47 UTC, segfaultxavi commented on README.md
> +In order to produce any output file the [catbuffer-generators](https://github.com/nemtech/catbuffer-generators) project is needed. Please see this project's usage examples.
Done

2020-10-23 14:47 UTC, segfaultxavi commented on README.md
> +> When no generator is given input files are parsed and checked for validity but not output files are created.
Done

2020-10-23 14:48 UTC, segfaultxavi commented on README.md
> +Using catbuffer-generators developers can generate builder classes for a given set of programming languages. For example, the [Symbol SDKs](https://nemtech.github.io/sdk) use the generated code to op
Done

2020-10-23 14:49 UTC, Jaguar0625 commented on README.md
> +scripts/generate_all.sh
i think it was 4.0 that was required.

2020-10-23 14:49 UTC, Jaguar0625 commented on README.md
>  Copyright (c) 2018 Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp Licensed under the [MIT License](LICENSE)
https://github.com/nemtech/catbuffer/commit/bb6e1b4d8575b665aac2f251c2ea25b2be2fef4a

2020-10-23 15:17 UTC, segfaultxavi commented on README.md
> +scripts/generate_all.sh
Added note on Bash 4 or higher.

2020-10-23 15:17 UTC, segfaultxavi commented on README.md
>  Copyright (c) 2018 Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp Licensed under the [MIT License](LICENSE)
Done

2020-10-23 15:22 UTC, Jaguar0625 approved these changes

2020-10-23 15:24 UTC, Jaguar0625 commented
Merged as 3b0a453.

2020-10-23 15:24 UTC, closed without merging