added finalized block
nemtech/catbuffer pull request #61
Opened 2020-10-28 00:08 UTC by Wayonb

2020-10-28 12:20 UTC, Jaguar0625 commented on schemas/finalization/FinalizedBlock.cats
> +struct FinalizedBlock
i assume this is supposed to match what is sent over ZMQ?

2020-10-28 12:21 UTC, Jaguar0625 commented on schemas/finalization/FinalizedBlock.cats
> +# binary layout for finalization block header
finalization => finalized?

2020-10-28 12:21 UTC, Jaguar0625 requested changes
please add to generate_all.sh

2020-10-28 13:50 UTC, Wayonb commented on schemas/finalization/FinalizedBlock.cats
> +struct FinalizedBlock
Yes.  I can name it the same if you want (PackedFinalizedBlockHeader)?  maybe that will be clearer.

2020-10-28 22:18 UTC, Jaguar0625 commented on schemas/finalization/packed_finalized_block_header.cats
> +	hash = Hash256
please add newline

2020-10-28 22:18 UTC, Jaguar0625 commented on schemas/types.cats
>  using FinalizationEpoch = uint32
please alphabetize

2020-10-28 22:18 UTC, Jaguar0625 commented on schemas/finalization/packed_finalized_block_header.cats
> +import "types.cats"
unneeded ?

2020-10-28 22:18 UTC, Jaguar0625 commented on schemas/finalization/FinalizedBlock.cats
> +struct FinalizedBlock
i would probably name it `FinalizedBlockHeader` (all catbuffer types are implicitly packed).

2020-10-30 11:52 UTC, Jaguar0625 requested changes

2020-10-30 11:52 UTC, Jaguar0625 commented on scripts/schema_lists.sh
> +	"finalization/finalized_block_header.cats")
1. no comma 
2. remove ".cats" file 

[this is causing travis to fail]

2020-10-30 11:52 UTC, Jaguar0625 commented on schemas/finalization/finalized_block_header.cats
> +# binary layout for packed finalized block header
~~packed~~

2020-10-30 11:52 UTC, Jaguar0625 commented on schemas/finalization/finalized_block_header.cats
> +	# block height
block => proof ?

2020-11-09 12:52 UTC, Jaguar0625 approved these changes

2020-11-09 12:52 UTC, merged